In [ ]:
import numpy as np
import pickle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
with open('/content/drive/MyDrive/RL/new/states.data', 'rb') as filehandle:
    # read the data as binary data stream
    STATES = pickle.load(filehandle)

In [ ]:
with open('/content/drive/MyDrive/RL/new/transition_prob.data', 'rb') as filehandle:
    # read the data as binary data stream
    transition_probability = pickle.load(filehandle)

In [ ]:
len(STATES)

3381

In [ ]:
STATES = np.asarray(STATES) 

In [ ]:
print(STATES[3380])

[2 2 1 2 1 1 1 2 1]


In [ ]:
def check_game_over_3(markers):
  game_over = False
  tie = False
  winner =0
  x_pos = 0
  for x in markers:
    #check columns
    if sum(x) == 3:
      winner = 1
      game_over = True
    if sum(x) == -3:
      winner = 2
      game_over = True
    
    #check rows
    if markers[0][x_pos] + markers [1][x_pos] + markers [2][x_pos] == 3:
      winner = 1
      game_over = True
    if markers[0][x_pos] + markers [1][x_pos] + markers [2][x_pos] == -3:
      winner = 2
      game_over = True
    x_pos += 1

  #check cross
  if markers[0][0] + markers[1][1] + markers [2][2] == 3 or markers[2][0] + markers[1][1] + markers [0][2] == 3:
    winner = 1
    game_over = True
  if markers[0][0] + markers[1][1] + markers [2][2] == -3 or markers[2][0] + markers[1][1] + markers [0][2] == -3:
    winner = 2
    game_over = True

  #check for tie
  if game_over == False:
    tie = True
    for row in markers:
      for i in row:
        if i == 0:
          tie = False
    #if it is a tie, then call game over and set winner to 0 (no one)
    if tie == True:
      game_over = True
      winner = 0
  return game_over,winner,tie
  # if game_over == False:

In [ ]:
def reward(y):
    r=0
    winner = 0
    y = np.array(y).reshape(3,3)
    y[np.where(y==2)] = -1
    go,winner,tie = check_game_over_3(y)
    if go == True:
        if winner == 1:
            r = 100
        elif winner == 2:
            r = -100
    if tie == True:
        r = 10
    return r

In [ ]:
REWARDS = np.array([0]*len(STATES))
for i in range(len(STATES)):
  REWARDS[i] = reward(STATES[i])

In [ ]:
with open('rewards.data','wb') as filehandle:
  pickle.dump(REWARDS, filehandle)

In [ ]:
A = np.zeros(9)
for a in range(9):
    for 

In [ ]:
W = np.array([0.0]*len(STATES))
pi_star = [0]*len(STATES)
gamma = 0.1

In [ ]:
for k in range(10):
    for i,s in enumerate(STATES):
        # print(i)
        Re =[-1000]*9
        for a in range(9):
          if s[a] == 0:
            R_bar_a = 0
            # for j in range(len(STATES)):
                # R = REWARDS[j]
            Re[a] = np.dot(transition_probability[i][a],REWARDS+gamma*W)
        print(i,Re)
            # Re[a] = R_bar_a+gamma*np.dot(transition_probability[i][a],W)
        W[i]= np.max(Re)
        pi_star[i] = np.argmax(Re)
    print(W)
    

In [ ]:
Re =[-1000]*9
i = 1250
for a in range(9):
    R_bar_a = 0
    # for j in range(len(STATES)):
        # R = REWARDS[j]
    Re[a] = np.dot(transition_probability[i][a],REWARDS+gamma*W)
print(i,Re)
    # Re[a] = R_bar_a+gamma*np.dot(transition_probability[i][a],W)
W[i]= np.max(Re)
pi_star[i] = np.argmax(Re)

1250 [0.0, -47.29991758357926, -44.71268202627609, 0.0, 0.0, -99.99038659793638, 0.0, 0.0, 0.0]


In [ ]:
W[1250]

0.0

In [ ]:
print(pi_star)

[0, 6, 3, 4, 2, 4, 1, 3, 6, 7, 7, 2, 2, 2, 0, 0, 0, 6, 5, 5, 0, 4, 0, 5, 4, 4, 4, 0, 6, 6, 5, 6, 5, 6, 8, 8, 6, 1, 5, 2, 3, 2, 3, 3, 8, 8, 8, 3, 3, 2, 7, 7, 7, 3, 7, 2, 0, 1, 8, 6, 8, 8, 4, 4, 4, 5, 7, 4, 5, 6, 7, 4, 4, 4, 7, 4, 8, 4, 6, 6, 6, 6, 4, 6, 6, 8, 8, 8, 8, 8, 6, 4, 8, 7, 4, 4, 3, 3, 4, 3, 3, 3, 3, 6, 8, 6, 8, 4, 3, 4, 4, 7, 4, 4, 4, 4, 6, 8, 4, 4, 3, 6, 6, 4, 6, 6, 8, 8, 8, 8, 5, 4, 6, 4, 4, 3, 8, 3, 3, 3, 3, 8, 6, 8, 4, 5, 4, 6, 4, 4, 4, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 8, 8, 8, 2, 2, 8, 8, 1, 5, 4, 4, 2, 8, 4, 1, 1, 5, 4, 4, 4, 2, 2, 2, 2, 1, 1, 1, 1, 6, 2, 6, 6, 2, 2, 6, 3, 3, 3, 3, 2, 2, 3, 2, 1, 2, 2, 2, 1, 1, 1, 8, 6, 6, 8, 8, 2, 3, 3, 1, 2, 4, 4, 2, 2, 1, 1, 8, 7, 8, 7, 8, 7, 1, 4, 2, 1, 6, 6, 6, 3, 6, 8, 4, 3, 6, 4, 4, 8, 7, 4, 5, 4, 7, 7, 7, 7, 6, 7, 4, 6, 8, 3, 4, 4, 7, 7, 8, 7, 2, 4, 4, 4, 8, 4, 4, 4, 7, 6, 5, 7, 3, 5, 6, 8, 4, 5, 5, 7, 7, 7, 0, 7, 4, 6, 4, 3, 4, 7, 7, 8, 3, 5, 4, 6, 4, 4, 4, 4, 6, 4, 4, 4, 0, 0, 0, 0, 0, 7, 7, 2, 7, 2, 0, 2, 7, 5, 4, 2, 4, 2, 4, 4, 

In [ ]:
with open('policy.data','wb') as filehandle:
  pickle.dump(pi_star, filehandle)

In [ ]:
te = STATES[123].copy()

In [ ]:
y = np.array(te).reshape(3,3)
y[np.where(y==2)] = -1
print(y)

[[ 1  0 -1]
 [ 1  0  0]
 [-1  0  0]]


In [ ]:
STATES[1250]


array([1, 0, 0, 1, 2, 0, 2, 2, 1])

In [ ]:
REWARDS[1250]

0

In [ ]:
pi_star[1250]

2

In [ ]:
for i in range(9):
  print(np.sum(transition_probability[1250][i]))

0.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
